### PR TITLE
Show mentor dashboard for project submitters

### PR DESCRIPTION
**Pull request by klappradla**
Hey @alicetragedy, this adds the changes specified in #648: submitters of accepted projects for the current season have access to the mentor dashboard during application phase.

The applications they see are of course also from the current season.

### CODE REVIEW

**Comment by carpodaster** [comment]
> I'm not sure it makes sense to allow both submitters AND users with role “Mentor” to view the dashboard as it wouldn't really solve our problem. wdyt?

I believe we only assign mentor roles when the team has been officially picked.

**Comment by alicetragedy** [comment]
@carpodaster Ah sorry, I think I am confused about the roles again... What's a person that is assigned to a team as a Mentor called? Currently there is the possibility for people that have been added to a team as “Mentors” to view the mentor dashboard — this PR would remove that possibility. so I was wondering whether we would still want that or not.

**Comment by mkalininait** [comment]
@alicetragedy maybe we just ignore those 3 projects where "submitters are not “necessarily” the final mentors" for the moment and implement a good, consistent solution for the next year? I'm a bit afraid of making the app logic even more complicated while fixing things in a rush. Maybe we could find custom workarounds for those 3 projects...

**Comment by alicetragedy** [comment]
anyone want to do the honours of pressing the Merge button? ;) :man_dancing:

**Pull request merged**
