### PR TITLE
Show Conferences and Updates in navigation only for admins #385

### PR DESCRIPTION
**Pull request by Nattivolk**
Wasn't sure what the condition should be, so I left it there for admins.

### CODE REVIEW

**Comment by alicetragedy** [comment]
I'm going to take a look at it tomorrow (ping @carpodaster && @ramonh if you get there before me)

**Comment by alicetragedy** [comment]
I've added some comments on things that need changing.. and I think after this, we'd be ready to go. could you make the changes tonight? You can ping me if you need anything!

**Comment by Nattivolk** [comment]
Changed the condition

**Comment by alicetragedy** [comment]
yay! thank you for doing this @Nattivolk, I'm sooo happy it's checked off the list :sparkles:

**Pull request merged**
