### PR TITLE
Dashboard styling

### PR DESCRIPTION
**Pull request by roosdebildt**
Adds styling to dashboard to make it responsive. (I opened a new branch to incorporate the many branches and closed the previous PR).

Looks like this:

screen shot 2015-09-24 at 14 55 30

screen shot 2015-09-24 at 15 08 00

### CODE REVIEW

**Comment by roosdebildt** [comment]
I can see it locally... and it shows like an `<a>`-tag inside the `<p>`?

**Comment by roosdebildt** [comment]
haha no worries, stay calm and drink your coffee. I'm done with this PR, so be caffeinated before you review and merge :) (merge this branch and not the old one, right?)

**Comment by roosdebildt** [comment]
btw @F3PiX wdyt of the icons/status as they look now?

**Comment by F3PiX** [comment]
Apart from that I love them: I liked the bigger ones better. Well, they were a bit tooo big, but I find them a bit too small now. I wouldn't mind if they take the room they deserve. It is quite an important part of the dashboard view, so they don't need to be shy. And because you ask ;-) I don't like the word 'status' in front of them. If their meaning is not clear at first sight, it _will_ be clear the next day ;-)

**Comment by roosdebildt** [comment]
Exactly the two things I was doubting about! :) Sometimes, you simply stare at the screen for too long. This better:

screen shot 2015-09-24 at 17 32 12

**Comment by alicetragedy** [comment]
@roosdebildt would you like me to merge already, or do you want to incorporate @F3PiX's feedback into this PR? let me know – I'm ready to press the button ;)

**Comment by F3PiX** [comment]
Sure! I feel like they are still floating a bit upwards. Maybe even a bit bigger? And/Or a slightly lower vertical position?

**Comment by roosdebildt** [comment]
screen shot 2015-09-24 at 18 48 49

done! is it ok if we merge this @F3PiX? I would really like to continue with the new files tomorrow! :)

**Comment by F3PiX** [comment]
They are supercute!

**Comment by F3PiX** [comment]
@alicetragedy Sorry for the delay! It is totally ready to merge. If you will do the honors... :-)

**Comment by alicetragedy** [comment]
:tada:

**Pull request merged**
