### PR TITLE
Add autocomplete to gender identity field and turn the field into single liner

### PR DESCRIPTION
**Pull request by ramonh**
This addresses #591 by both adding autocomplete to the gender identity field, as well as turning the field itself into a single line textfield from a 2-line text area.

The values for identities come from the proposal [here](https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/591#issuecomment-273421058).

### CODE REVIEW

**Comment by carpodaster** [comment]
I checked it out locally - looks good! One thing I did notice though: I can imagine many applicants want to just enter "female", possibly meaning "cisgender female" because not everyone is familiar with the more specific gender terms. "female" doesn't trigger the autocomplete list, suggesting that it's a "wrong answer"?

This is nothing about this PR but more about either the list of autocomplete options or the way jQuery Autocomplete works.

**Comment by alicetragedy** [comment]
@carpodaster yeah that's a good point.. but typing “Woman” works (as we have “Cisgender Woman“ and “Transgender Woman” as options), so it's not really an issue of how the autocomplete works, more a problem of the original list I made. We could definitely add the option “Female” maybe? wdyt @ramonh?

**Comment by ramonh** [comment]
Could definitely do, @alicetragedy. Thanks for the feedback, @carpodaster! 

In your opinion, should this be a separate commit for documentations' sake, or just squashed? Or am I perhaps overthinking this 😨

**Comment by alicetragedy** [comment]
@ramonh I have no real opinion there, but I think squashed sounds good 👍

**Comment by ramonh** [comment]
Alrighty, I've added the field! Thanks again for the feedback.

**Comment by alicetragedy** [comment]
I'm going to go ahead and merge this.... #yolomerge

**Pull request merged**
