### PR TITLE
fixed up form styles #126

### PR DESCRIPTION
**Pull request by sareg0**

### CODE REVIEW

**Comment by carpodaster** [comment]
Hey @sareg0, thanks for the work on this! The forms look way better :rocket: 

I've spotted a small regression but I don't know if it's only me: The nav elements have fallen out of the red box.

screen shot 2015-03-01 at 17 22 13

**Comment by carpodaster** [comment]
http://2.bp.blogspot.com/-41v6n3Vaf5s/UeRN_XJ0keI/AAAAAAAAN2Y/YxIHhddGiaw/s1600/css.gif

**Comment by alicetragedy** [comment]
hahaha, that's soooo weird. It totally looks alright for me, both in Chrome and FF. Which browser are you using, @carpodaster?

**Comment by carpodaster** [comment]
I'm on FF as well. Do you have the 'Apply now' already? Maybe that's the additional menu item that makes it fall apart.

**Comment by alicetragedy** [comment]
a new flavour of CSS: MysteryCSS.


screen shot 2015-03-01 at 17 49 04

**Comment by carpodaster** [comment]
Ok, this is weird. Safari + Chromium are playing nice as well and so does FF on my Macbook. No idea why my iMac is being naughty – but then it's indeed just me. Meeerge!

**Comment by sareg0** [comment]
hahah! I must admit, I looked like Peter Griffin messing with the CSS on this one, and the slim... holy cow... Me no likee

**Pull request merged**
