### PR TITLE
User/tshirt cut

### PR DESCRIPTION
**Pull request by branquinhoaa**
PR related to the issue  #788

- include column tshirt_cut in the user model
- include a select dropdown to choose the t-shirt cut
- show the selected t-shirt cut where t-shirt size is shown

### orga user info
orga_user_info_before
### show user
show_user_before
### edit user
tshirt_before

### orga user info
orga_user_info_after

### show user
show_user_after

### edit user
tshirt_after

### CODE REVIEW

**Comment by mkalininait** [comment]
@carpodaster Yes, I think we should allow the blank option.

**Comment by mkalininait** [comment]
@branquinhoaa Could you please add the new field to `app/exporters/users.rb`? Thanks!

**Comment by mkalininait** [comment]
@branquinhoaa The exporter fix looks good to me!
The 'allow blank value' change I didn't test. But I trust your testing.
Interesting note: the 'blank' value of 'tshirt_size' is set to false, but I still can set the blank value:
`= f.input :tshirt_size, as: :select, collection: User::TSHIRT_SIZES.map { |k| [k, k] }, label: 'T-Shirt size', blank: false, required: false` I like the behaviour, I just wonder why it works this way...

Anyway, I think we can merge this PR, unless @carpodaster has a different opinion :)

**Comment by carpodaster** [comment]
> […] unless @carpodaster has a different opinion :)

He doesn't ^^

LGTM!

**Pull request merged**
