### PR TITLE
a friendlier application draft form

### PR DESCRIPTION
**Pull request by michaelem**
This adds a separate tab for the application and validity buttons in the application draft form. Further it disables the 'apply' & 'check validity' if the user changes anything in the form. This takes care of #202 (in a way).

### CODE REVIEW

**Comment by michaelem** [comment]
@alicetragedy what do you think?

**Comment by alicetragedy** [comment]
This is definitely a lot better, especially when it comes to locking the validity check — thanks for this! 
I did first a quick review of the code which looked fine :+1: but when running it locally on an invalid form, clicking "Check validity" doesn't show me any error message and shows the success notice "Your application draft was saved." 
In itself, this isn't a huuuuge problem since we had some duplicate messages anyway but a) I want to find out why the error messages are not being shown anymore and b) because of how the required fields for the student, which are attached to the student model, are set up (see in `student.rb`), field validations are not shown in the "About You" tab the same way they are in the other ones. This is sort of a bummer, and I am not sure how to fix it. 😕

**Comment by michaelem** [comment]
as for a) I think I know why: the button is now inside the form tag and triggers a submit of the entire form. I think I can just switch to a link though.

**Comment by michaelem** [comment]
at least a) should be fixed now :)

**Comment by alicetragedy** [comment]
yay!!!!! thank you @michaelem :tada: :confetti_ball:

**Pull request merged**
