### PR TITLE
add some bootstrap magic to the teams form, close #152

### LINKED ISSUE #152: Team form: Adding roles / sources
* [x] teams form: roles
* [x] teams form: soures
* [ ] user editing: roles

Some nested form elements could need some styling, @lislis maybe? :smile_cat: 

--------------------

**teams/new: editing roles**
screen shot 2015-03-05 at 00 23 56

--------------------

**teams/new: editing sources** (comments see above)

screen shot 2015-03-05 at 00 45 58
--------------------

**users/new: editing roles**

screen shot 2015-03-05 at 00 38 11

### PR DESCRIPTION
**Pull request by lislis**
I can't do pixel perfect alignment since the nesting of the form elements is kind of scary (no offense!).
I don't want to touch the javascript right now, but if the 'add team member' forms were appended differently one could use the bootstrap grid as it should be.
But that's a different story

### CODE REVIEW

**Comment by carpodaster** [comment]
Very cool :+1:    I don't have the time to check it out locally at the moment – do you have a screenie? But even if you don't: feel free to merge! :shipit:

**Comment by lislis** [comment]
screen shot 2015-03-13 at 16 37 45
like this

**Comment by carpodaster** [comment]
Awesome, @lislis  – ¡muchas gracias!

**Comment by alicetragedy** [comment]
:heart_eyes:

**Comment by sareg0** [comment]
looks super!!

**Pull request merged**
