### PR TITLE
Add apply validations for new application draft fields

### PR DESCRIPTION
**Pull request by ramonh**
This addresses #402

### CODE REVIEW

**Comment by alicetragedy** [comment]
@ramonh If possible, could you make a new PR against `application-process-2016` instead? If that's not possible or too much trouble, we can also merge this and then merge master into it — it's just that the branch currently deploys automatically to the test app Carsten set up, so it makes it quite easy for quick fixes :)

**Comment by alicetragedy** [comment]
awesome, thanks for this @ramonh!

**Comment by ramonh** [comment]
Sorry I couldn't get to this request sooner. :broken_heart:

**Comment by alicetragedy** [comment]
@ramonh no worries, it all worked out fine!

**Pull request merged**
