### PR TITLE
Add validation to limit the max. number of students per team

### PR DESCRIPTION
**Pull request by klappradla**
Validation for the teams model to limit the max. number of students to two. Editing and deleting roles, etc. are taken into account, the validation process takes place in memory, not relying on data yet to be persisted.

ace624f adds the validation for the team model.

dda1f8f adds the classic behavior of firing the team's validations when saving a role, which will add the default Rails error message to the role: **`Team is invalid`**. I personally don't like this behavior, as I think it doesn't provide meaningful insights to the user. It rather adds complexity for her to understand what went wrong (*"2 errors prohibited this role from being saved ... Team is invalid"*).

Therefore 50812f9 undos firing the team model's validations when saving a role and instead displays the team's own error message in the role's form, if adding/editing a role does not suit the constraints of the team the role is connected to. As the **`Add a member`** button in the team's show view is just a shortcut duplicating the behavior of the normal **`Edit`**, the team-context is obvious anyways, so I consider showing the team errors more useful here.

If you don't like this approach, you can either just discard the last commit (50812f9) or tell me to rework it. If you like it, I would further suggest to fully ditch the **`Add a member`** button as it is available in an approachable way within the team's form anyways.

9c349da fixes some minor problems I ran into when bootstrapping the project.

### CODE REVIEW

**Comment by carpodaster** [comment]
Hey @klappradla - looks awesome, thank you!

As for the `Add a member` button: sure, let's remove it, but let's merge this PR first.

**Comment by klappradla** [comment]
👍 I'll assign #205 to me and continue from there.

**Comment by ramonh** [comment]
:tada: Thank you @klappradla!

**Comment by alicetragedy** [comment]
awesomeeee!! thanks! :confetti_ball:

**Pull request merged**
