### PR TITLE
WIP: Refactor current into in_current_season

### PR DESCRIPTION
**Pull request by F3PiX**
Touches #493

- [x] Step 1: the Team.in_current_season scope
- [ ] Refactor other models' current scope (application_draft,  conference, project, student)  
        - [x] Check what to do with the current scope in Exporters 
- [ ] Refactor other references (in exporters, etc) 
- [ ] Refactor traits in factories plus seeds.rb

@carpodaster Right?

### CODE REVIEW

**Comment by F3PiX** [comment]
EDIT I have serious doubts if we want to follow through. It is not super useful to only rename the :current scope in Team. With every step down the to do list, the refactoring becomes reaaaally cumbersome. At the end of the to do list, I had over 150 broken tests. HAHAHA.

**Comment by carpodaster** [comment]
Hej @F3PiX. Yeah, I can image a lot of broken tests. Your TODO list above looks good 👍 

As for the usefulness: sure, it doesn't improve code quality as reported by CodeClimate and it doesn't speed up things. It "only" improves code readability and the impact of that is very hard to measure. Personally, I think the changed scope better reveals the intention and I think it would be a valuable contribution. If it's too much work: let's not do it.

**Comment by F3PiX** [comment]
I'll have a look again with a different approach. It is a lot of work, it is also a valuable lesson on refactoring (and of being careful what you wish for LOL).  Thnx.

**Comment by F3PiX** [comment]
Continued as #513 after rebasing

**Pull request closed without merging**
