### PR TITLE
FIX: performance evaluation should not change when called multiple times

### PR DESCRIPTION
**Pull request by michaelem**
This fixes a bug (that was probably not occurring in the app directly) where each time evaluation was called the resulting score would be added to the last score (so after a few calls it would be higher than it should be). Since it's mostly your code @F3PiX, does this look fine to you?

(I found this while building the log update reminder in #256 which I'll add to this class as well, that is the reason why I also moved the self.buffer_days? method to a class method.)

### CODE REVIEW

**Comment by carpodaster** [comment]
@michaelem I know there hasn't been a test to begin with, but would you mind adding one?

**Comment by michaelem** [comment]
yes, will do so today (THB I was just too tired yesterday 🙈)

**Comment by michaelem** [comment]
Added a spec for the class, I'm not that handy with rspec yet (I am more used to minitest), if anyone has suggestions for improvements please let me know.

**Comment by klappradla** [comment]
Hey @michaelem, from a quick look at your tests (I might be wrong), it seems like you're using the *should*-syntax as opposed to the *expect*-syntax RSpec [introduced some time ago](http://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/) and recommends to use. It's quite easy to [switch to this syntax](https://github.com/rspec/rspec-expectations/blob/master/Should.md) though. If your browser is not used to it, googling for the syntax tends to bring you to the old docs.... [these](https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers) are the current ones.

**Comment by michaelem** [comment]
@klappradla omg, yes, I did not realise I was using the old syntax. Shouldn't (haha) I get warnings by now for doing so? I'll dig out transpec tonight.

Additional though: I'd disable the should syntax entirely?

**Comment by klappradla** [comment]
Well, they just *encourage* you to use the expect-syntax, not **force**, since there seem to be some cases where you could prefer it... so maybe that's why there are no deprecation warnings. It will at some point maybe extract into a gem - so they kinda seem to want to get rid of it 😉 

Disabling it entirely, don't know if really necessary, but you could give it a try:
```ruby
RSpec.configure do |config|
  config.expect_with :rspec do |c|
    c.syntax = :expect             # disables `should`
    # or
    c.syntax = :should             # disables `expect`
    # or
    c.syntax = [:should, :expect]  # default, enables both `should` and `expect`
  end
end
```

**Comment by michaelem** [comment]
Changed to the new syntax (and amended to the old commit).

**Comment by F3PiX** [comment]
I am VERY happy that you improved this. 🙇  And even more that you added tests...

**Comment by carpodaster** [comment]
Looks good! ✨

**Pull request merged**
