### PR TITLE
Fix error caused by teams deleted post-application

### PR DESCRIPTION
**Pull request by ramonh**
Fingers crossed, this should eliminate the error caused by trying to list the rating section's applications

### CODE REVIEW

**Comment by alicetragedy** [comment]
looks good @ramonh, I think we can merge!! ✨

**Comment by ramonh** [comment]
Nice! Thank you for having a look @alicetragedy!

**Comment by alicetragedy** [comment]
#yolo

**Comment by ramonh** [comment]
Seems to work now, thank you so much @alicetragedy!

**Pull request merged**
