### PR TITLE
Style and relocate search for users, small style changes to selection box

### PR DESCRIPTION
**Pull request by katrin-k**
Here's what I did in detail, following the list of changes below:
In `global.sass`
- The filter/selection box got a border for better visibility.
- On activities page, the filter for teams got a small margin towards the select dropdown. 
- Styles for the search bar used on community page

In `users/_roles…` and `users/index…`
- Relocate the search bar to be part of the filter/selection box
- Relocate the h4 "Role" to be part of the filter/selection box

In `users/_search…`
- Add button classes.

Edit: Referencing it to #379 for completeness

### CODE REVIEW

**Comment by carpodaster** [comment]
Hello @katrin-k! I'm pretty sure, it looks awesome but could you attach a screenshot or two?

**Comment by katrin-k** [comment]
There you go. 
On the activities page, it's just a little more space between the Team selection dropdown and the label. Almost not noticable ;). 

pr searchbar

I'll also keep in mind to to assign correct labels for the PRs.

**Comment by carpodaster** [comment]
🎊

**Comment by katrin-k** [comment]
\o/

**Comment by ramonh** [comment]
Yay 🚀

**Comment by F3PiX** [comment]
🎉  💓  ✨

**Pull request merged**
