### PR TITLE
Add anti bias warning to application form

### PR DESCRIPTION
**Pull request by F3PiX**
Solves #587 

I copied your sentence, @mkalininait, only put 'please' at the end of the sentence, because I learned recently that 'please' upfront sounds rude to native English speakers?

### CODE REVIEW

**Comment by F3PiX** [comment]
"The questions below" looks confusing to me. It does not apply to the financial part, because there they are _supposed_ to mention the location. 
Also, not sure about the English. Do we have native English speakers in da house?

**Comment by F3PiX** [comment]
schermafbeelding 2017-01-10 om 12 34 30

**Comment by mkalininait** [comment]
@F3PiX Thank you for the fix.
We can rephrase the warning. Any suggestions?
Regarding the financial part: it doesn't really matter if the students mention their location in the financial fields or not. We don't see them during the blind phase of selection. We look at them afterwards, during the next non-blind phase, and then the "Location" field is already available.

**Comment by F3PiX** [comment]
I don't have further suggestions for the phrase.

**Comment by alicetragedy** [comment]
While I'm not a native native speaker, all of my secondary school education was in an English school, so I think my level is pretty good :) I wouldn't consider “Please do this and this” as 'rude' to English speakers, it just might sound less friendly and is used more in written notices (e.g. instructions) than in the spoken, everyday language. 
I can definitely double-check this with a native speaker at the office tomorrow, but using “Please” at the front of a sentence is always my preferred variant, because it's more common and what people are used to.

About an alternative to “in your answers below”:  maybe we could refer to “Background information” to make our message clearer? Something like, “Please don't mention any specific names (e.g. geographical features, universities, companies, etc...) that may point to your location in the “Background Information” fields. This will avoid bias in the selection process.”

**Comment by F3PiX** [comment]
@alicetragedy Cool! That counts as native in my book ;-) 
As I understood, the message applies to more than the Background Information. 
How about you and @mkalininait decide on the final phrase?

**Comment by alicetragedy** [comment]
sounds good @F3PiX! 👍

**Comment by mkalininait** [comment]
@F3PiX One more suggestion. 
I would add the class `.alert` to the message. It will set necessary paddings. Some info about the Bootstrap alerts: http://www.w3schools.com/bootstrap/bootstrap_alerts.asp

Here is how it would look like with the `.alert` class:
screen shot 2017-01-10 at 22 38 08

```
.alert.alert-warning
    strong Warning: 
    | In your answers below, don't mention names (geographical features, universities, companies etc.) that can point to your location, please. This is to avoid bias in the selection process.
```
(The message is still to be corrected)

**Comment by mkalininait** [comment]
@F3PiX We discussed the warning message with @alicetragedy and agreed on the following text:
"Please don't mention any specific names (e.g. geographical features, universities, companies, etc...) that may point to your location in any of the following fields. This will avoid bias in the selection process." Does it sound good to you?
Would you like to make the final changes yourself or would you like me to make them?

**Comment by carpodaster** [comment]
@F3PiX can you add one final schermafbeelding (I ❤️ this word so much!)? I think we're ready to merge then.

**Comment by F3PiX** [comment]
One schermafbeelding coming up! 
schermafbeelding 2017-01-11 om 21 47 00

**Comment by carpodaster** [comment]
@mkalininait are you cool with the changes?

**Comment by mkalininait** [comment]
@carpodaster yes!
@F3PiX thank you!

**Pull request merged**
