### PR TITLE
Style "Clear search" link and remove when there are no search params

### PR DESCRIPTION
**Pull request by katrin-k**
This belongs to PR #508. 

508 no search param
508 search param

### CODE REVIEW

**Comment by F3PiX** [comment]
Looks nice @katrin-k !! 🎈  
About the double PR: I think it would be best to close the original one (#508) and take this one to merge. 
Do you agree?

**Comment by katrin-k** [comment]
@F3PiX I agree :).  And will close #508 

@carpodaster Looks good to go

**Comment by F3PiX** [comment]
@ramonh Hi Ramon, could you please have a look? Can we merge?

**Comment by ramonh** [comment]
Looks fantastic, thank you so much! 🎉

**Pull request merged**
