### PR TITLE
add tabs for application form

### PR DESCRIPTION
**Pull request by alicetragedy**

### CODE REVIEW

**Comment by alicetragedy** [comment]
@carpodaster @lucaspinto this should take care of the tab issue. feel free to look over it, and make changes as you see fit. :)

**Comment by lucaspinto** [comment]
This is perfect.

**Comment by carpodaster** [comment]
Cool, @alicetragedy ! Can you still modify the PR so that it aims to be merged into the `application-process-2016` remote branch?

If this is too much hazzle, don't bother; we can just merge it into master and then back into the feature branch from there.

**Comment by alicetragedy** [comment]
@carpodaster no problem! I can close this one and push a new branch for a new PR (I don't think it's possible to modify the base branch of a pull request after it's been made).

**Comment by carpodaster** [comment]
Closed in favor of #384

**Pull request closed without merging**
