### PR TITLE
 Upgrade/rails to 4.2

### PR DESCRIPTION
**Pull request by pxlpnk**
This is a dirty merge version. 
I couldn't find another way of handling it in a cleaner way

### CODE REVIEW

**Comment by carpodaster** [comment]
Thanks @pxlpnk ! Will deploy this on staging and after that I think we're ready to go :rocket:

**Comment by pxlpnk** [comment]
Unmergable again ):

**Comment by pxlpnk** [comment]
The best is probably to merge it from the command line. PR's are rendered to easy useless with that amount of changes

**Comment by carpodaster** [comment]
Yeah, agreed: there are currently too many changes in master for big PRs like that. Probably best to wait until after April 14th when we close applications. Just to circumvent the hypothetical event of the odd hidden regression.

**Comment by pxlpnk** [comment]
fair enough. lets close this one then and restart from the original PR once the time is ready

**Comment by carpodaster** [comment]
@pxlpnk Now that we're done with the application phase, would you have time to give this another try?

**Pull request closed without merging**
