### PR TITLE
Link to team page instead of redirecting to it

### PR DESCRIPTION
**Pull request by ramonh**
This addresses part of #419 by linking to the team page instead of redirecting to it (Thank you @alicetragedy for the suggestion!)

### CODE REVIEW

**Comment by alicetragedy** [comment]
sorry @ramonh I'm being a pain :D but I'd love for you to make that tiny change before we merge. thank you!

**Comment by ramonh** [comment]
Please never apologize for fixing wording. It's a weak point of mine and I appreciate the feedback! I'll fix it right away

**Comment by ramonh** [comment]
Just squashed it!

**Comment by alicetragedy** [comment]
awesomeeeee!!! :tada: :confetti_ball:

**Pull request merged**
