### PR TITLE
Style improvements

### PR DESCRIPTION
**Pull request by roosdebildt**
General styling more in line with railsgirlssummerofcode.com:

deletes non-functioning color-stack and creates new one with matching colors
adds Lato font-stack
restructures folders and files to better control separate stylings and their order
removes border-radius of avatars and other images

### CODE REVIEW

**Comment by alicetragedy** [comment]
@roosdebildt I'll take a look at the latest changes (the last commit specifically) and happy to merge after that. don't know if @carpodaster has any additional comments :)

**Comment by roosdebildt** [comment]
yeay, that would be great! so excited to work with the new files :dancers:

**Comment by carpodaster** [comment]
To the greater audience, since I have no experience with reviewing style-based PRs: I think it would be good to provide some screenshots with the changes since otherwise everyone has to check out the PR branch and click through everything, not really knowing where to look.

That being said, I'm sure it looks super awesome :ribbon: I'm not sure if we need a different font-face though.

**Comment by roosdebildt** [comment]
@carpodaster I integrated the new font-face and colors so that the app aligns with the styling of railsgirlssummerofcode.com. So that when you click on the "Home" button, the styling doesn't completely change and it's clear that the teams-app is part of RGSoC.

Here you go:

style-improvements

screen shot 2015-07-21 at 14 28 23

screen shot 2015-07-21 at 14 32 09

**Comment by roosdebildt** [comment]
Now that we're at it:

screen shot 2015-07-21 at 15 10 13

Thanks for rubber-ducking me @carpodaster :smile:

**Comment by alicetragedy** [comment]
@roosdebildt was there a specific reason for removing the border-radius on team images? I know that eg. on the team page on the rgsoc.org website, we have completely circular avatars, on the activities feed it's fully square, and in the list of teams it's with that border-radius, so it doesn't all fit together and is inconsistent. Is the plan to rework it so that it has one consistent style everywhere, or do you think it generally looks better square than with slightly rounded edges? 
this is an actual question, I don't necessarily have an opinion other than I quite like rounded borders :blush:

**Comment by alicetragedy** [comment]
other than my question above, which is not particularly important, I'm happy to click the green button :)

**Comment by F3PiX** [comment]
\0/ :+1:

**Comment by roosdebildt** [comment]
@alicetragedy in general, I like lay-outs with square boxes. I thought it would be nice to have more of a "flat layout" throughout the site. Also, I think it looks nice on the activity stream and for consistency I thought I'd change it on all pages. Wdyt? If you are ok with that, click the green button :)

**Comment by alicetragedy** [comment]
@roosdebildt fair enough! :+1:

**Pull request merged**
