### PR TITLE
[#583] Application Form: add a community involvement section

### LINKED ISSUE #583: Application Form: add a community involvement section
This would allow us to separate entirely programming skills from community involvement.

- Create a “Community Involvement” section (maybe somewhere between "Background information" and "Your programming skills")
- Move community-related fields ("Tell us about your community involvement") from the "Your programming skills" section to the newly created “Community Involvement” section.
- Add a new field "What do you think you could give back to the community?". 
- Remove the "giving back" part from the field "Why are you applying to this program".

### PR DESCRIPTION
**Pull request by bitboxer**
closes #583

### CODE REVIEW

**Comment by bitboxer** [comment]
@carpodaster should I fix the merge conflicts here?

**Comment by carpodaster** [comment]
@bitboxer oh yes, please :bowing_man:

**Comment by bitboxer** [comment]
rebased

**Comment by carpodaster** [comment]
:+1:

**Pull request merged**
