### PR TITLE
Navigation improvements

### PR DESCRIPTION
**Pull request by michaelem**
I've just started trying to implement the changes mentioned in #40 but got super annoyed by the navigation. Here is a small PR that adds breadcrumb navigation and a small overview so one has not to remember and type url's all the time.

### CODE REVIEW

**Comment by alicetragedy** [comment]
PRs that happen out of frustration are the best kind ;)
If no one else has gotten to it by tomorrow morning, I'll take a look at it then. I hope it's okay 😴

**Comment by klappradla** [comment]
I don't really get Travis' errors - seems something with Code Climate's API is going wrong?

**Comment by michaelem** [comment]
@klappradla me neither, felt like staring at a [guru meditaion error](https://en.wikipedia.org/wiki/Guru_Meditation)

**Comment by klappradla** [comment]
I just restarted em - let's see 🙈

**Comment by michaelem** [comment]
merged @klappradla was right next to me approving ;)

**Pull request merged**
