### PR TITLE
Create PR template

### PR DESCRIPTION
**Pull request by F3PiX**
Related issue # --

Adding a template for PR's, to help write concise and complete descriptions

### CODE REVIEW

**Comment by klappradla** [comment]
Solid work @F3PiX 💪 

I would have put it a bit more pressing for user interaction (editing, removing, checking things), just to make sure people will at least be forced to write something 😉 

Also, I would skip the "notes" part (this can be part of the description) and maybe merge "goal" and "description" as I find it very difficult to make a distinction between them without constantly crossing the boarders.

And one question: what do you mean with "Test/outcome"? 

Here my more interactive version (raw .md)

```markdown
{link targeted issue(s) and describe what this is doing}

#### preflight checklist 🚀
*[ ] tests added
*[ ] screenshot, gif or video added (check if no visual changes)
```

I know this ☝️ looks super short 😂  but for me it covers the key things _(I also don't wanna overwhelm people and make this a huge effort...)

**Comment by F3PiX** [comment]
Thanks Max! 
Let's collect other people's input before we decide, okay?

A note on the difference in our approaches: 
As the main goal of the template is to make reviewers' life easier, I'd say the template should first of all help juniors write better PR descriptions. 
From my experience as a junior, it can be surprisingly hard to be both concise and complete in reasoning about what a PR is doing. My idea (and experience) is that a little help with captions help me to achieve that. 

For fun: compare https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/758 and https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/300 and https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/273 🙄 

That said, we could give some direction to what a 'goal' is. Like : "Name the kind of change (for instance feature:, fix:, design:), give it a name, and add the main location in the code. Details go into the Description. 
For instance: "Feature: create CoffeePicker in Student Dashboard"

And an answer to your question about 'Test/outcome':  
<! --- How did you test? How can a code reviewer test? -- > Let's skip this all together. 🔥

**Comment by klappradla** [comment]
Ok, I get your point about guiding people to write better descriptions 💡 
For the testing part: I don't see how this can make the whole process around PRs more efficient. For quickly understanding and judging the code, it's useful to know if there are new automated tests covering the changes (and see if they make sense) yes or no. Whether or not the author tested the features in the browser, deployed a private app somewhere to test it... is not super useful information for quickly knowing if this PR makes sense / what changes it needs.
Similar for "how can a code reviewer test": it's obvious that I could in theory check out the PR locally and invoke the code or look at what Travis did with the tests. Whether I would do local testing with a production database dump, run it in multiple browsers, etc. is more of the reviewers own workflow, the author of the code does not really need to think about these things in too much detail upfront for the reviewer I'd say _(it's not really part of the contribution - although it's of course a nice help at times)_

So merging what you wrote with my previous comment, I'd update my solution to this:
```markdown
<!--- link the issue(s) this is targeting --->

<!--- describe what this is changing, what the code is doing -->

#### preflight checklist 🚀
*[ ] tests added
*[ ] screenshot, gif or video added (only if changes to the UI)
```

**Comment by klappradla** [comment]
Any more input on this?

**Comment by carpodaster** [comment]
Hey @F3PiX  and @klappradla !

As stated via Slack, I am not a huge fan of PR templates.

Even with `<!-- comments like this --->` I foresee a lot of placeholder clutter remaining in the PR.

I don't think we need to make the preflight checklist a checkable GHFMD list. It should be a reminder for the person lodging the PR, not being checked after the PR is created. We don't need an extra checklist to see if there are tests - we can have a look at the diff.

I wouldn't encourage new people to use the keywords _closes_ and _fixes_ as this will introduce a post-hook. It is perfectly fine for ongoing contributors who know their way around the app.

My idea of a PR template would look a bit like this:

> (Describe what this PR is about - what feature does it add, which bug does it fix? Link related issues. Tests are much appreciated. Add screenshots/gifs if your PR includes visual changes)

Quite spartan, I know

**Comment by F3PiX** [comment]
I actually like the spartan one very much. Except for the gifs 😂 . 

I'd say: let's start with the spartan one, and see how it works.  Okay? 

I'll make a note to ask for evaluations later.

**Comment by carpodaster** [comment]
> I actually like the spartan one very much. Except for the gifs 😂 .

what's wrong with gifs?

**Comment by klappradla** [comment]
Nice explanation @carpodaster 💚 +1 on using your puristic template 🎉 

Your abbreviation game is way to strong for me though 🙈  What's `GHFMD `? Googling I just find [this](http://journals.sagepub.com/doi/abs/10.1177/0008068320000107) 🤔

**Comment by carpodaster** [comment]
> Generalized Hypergeometric Factorial Moment Distribution of Order k

🤣 

I was thinking [GitHub flavoured markdown](https://github.github.com/gfm/), but they abbreviate it GFM. Oh well.

**Comment by F3PiX** [comment]
🤣

**Comment by F3PiX** [comment]
If only we had a label to tell that this is ready to be merged..... 😂

**Pull request merged**
