### PR TITLE
Upgrade to MRI v2.5.1

### PR DESCRIPTION
**Pull request by carpodaster**

### CODE REVIEW

**Comment by klappradla** [comment]
🔴 on CI. Probably a caching thing - will try with a restart first.

**Comment by carpodaster** [comment]
@klappradla it was a known issue. Fixed it by always installing a fresh bundler.

**Comment by carpodaster** [comment]
(Deployed it to staging to QA, but the DB seems stale – need to copy the prod DB one other time. Or if somebody has time to do that before tonight…?)

**Comment by carpodaster** [comment]
@klappradla sorry. Yes, I meant copying the production DB to staging

**Comment by klappradla** [comment]
Ok, I can do it now 🚜

**Comment by klappradla** [comment]
😹 done but:
screen shot 2018-04-03 at 22 49 21

**Comment by klappradla** [comment]
But from clicking around it looks like everything is behaving solid ⛰ 

Any hints on which tables I could truncate a bit? We're still 9k over the limit 🙈 Aside that, I'd say let's merge this ⛵️

**Pull request merged**
