### PR TITLE
Conferences/create none option

### PR DESCRIPTION
**Pull request by branquinhoaa**
PR related with the issue #806 

- create none option for team

### CODE REVIEW

**Comment by branquinhoaa** [comment]
@mkalininait :+1: 
Just some things:
- not sure about the name 'none'. 
- there is a strange behavior in the form: the destroy only works if I explicitly pass the object id it in the view... no idea why!

**Comment by mkalininait** [comment]
@branquinhoaa I didn't manage to make it run locally yet; I get some errors I don't understand yet ("undefined method `stringify_keys' for "/conferences/new":String", app/views/teams/edit.html.slim, line 14). Maybe I'll resolve it tomorrow.

>there is a strange behavior in the form: the destroy only works if I explicitly pass the object id it in the view... no idea why!

Could you please clarify what you mean by this?

**Comment by branquinhoaa** [comment]
@mkalininait
weird, I'm not getting errors in my local environment... 
Did you discover what is wrong?

about my comment:
'there is a strange behavior in the form: the destroy only works if I explicitly pass the object id it in the view... no idea why!'

I mean that I had to put the conference_id in the form, otherwise the controller did not recognize it.

**Comment by mkalininait** [comment]
@branquinhoaa I don't know, maybe I did something wrong with merges. I was missing the column `conference_preferences.team_id` after checkout/pull and tried to merge with `juuh42dias:conferences/aditional-info`. It helped but caused the error above.

**Comment by mkalininait** [comment]
@branquinhoaa I managed to run the PR locally. It seems to work!
One minor thing: before User saves her preferences for the first time, she sees both 'none' and 'conference' options. Why do we need the 'conference' option? It disappears once User saves preferences. And in general it looks useless in presence of the 'none' option.

**Comment by mkalininait** [comment]
@branquinhoaa 

> there is a strange behavior in the form: the destroy only works if I explicitly pass the object id it in the view... no idea why!
> I mean that I had to put the conference_id in the form, otherwise the controller did not recognize it.

¯\_(ツ)_/¯ 
Maybe @carpodaster knows.

**Comment by mkalininait** [comment]
@branquinhoaa Works perfect! Good to merge from my side!

**Comment by mkalininait** [comment]
Hey @klappradla This is a very little PR, do you think we can merge it? It's good to go from my side.
Not sure when Carsten will be able to look at it...

**Comment by branquinhoaa** [comment]
Hey @klappradla, I think this PR is no longer useful after all the changes in ConferencePreference model (PR  #810). 
I was passing a _destroy: true in the cases when I needed to destroy the conference, but now we cannot do that (I guess)...
What do you think?

**Comment by klappradla** [comment]
Sorry for coming back to this so late - my brain is kinda melted today 🙈 

You're right @mkalininait this could _"theoretically"_ be merged, I don't see a problem. However and there you're right @branquinhoaa it indeed does not make too much sense when combined with the changes we agreed upon for #810 .

Therefore I'd rather close this one in order to not introduce code that's not tested (the Javascript code) and that we'll with 100% certainty want to get rid off within implementing the next issues anyways. Are you both fine with that?

Aside that @branquinhoaa you're approach for passing the `_destroy` is totally valid 👍  I'd have probably solved it differently and also for the sake of easier testability without feature specs would have preferred a way of doing it _without_ Javascript, but that comes down to personal preference :v:

**Pull request closed without merging**
