### PR TITLE
Add edit functionality for projects

### PR DESCRIPTION
**Pull request by ramonh**
This adds the `U` in `CRUD`. :)

Once edited, the submitter would be redirected back to the list.

Only projects submitted by the user can be edited by that user.

### CODE REVIEW

**Comment by ramonh** [comment]
Another one coming in! @carpodaster, would you mind please taking a glance, please? :) It should be very similar to my last PR.

**Comment by carpodaster** [comment]
:+1: Thanks!

**Comment by ramonh** [comment]
Awesome! Does this wrap up #327?

**Comment by carpodaster** [comment]
We'd still have the 'D', but I don't know how we go about this. Just delete the project? Or just flag it as "deleted'" w/o actually deleting it?

**Comment by ramonh** [comment]
Ah woops, thought I'd seen that in the 'orga' view. Makes sense, Thank you!



—
Ramón Huidobro



http://ramonhuidobro.com

**Comment by ramonh** [comment]
I'll move the discussion back to the issue

**Pull request merged**
