### PR TITLE
Help page improvements

### PR DESCRIPTION
**Pull request by alicetragedy**
Closes https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/614

### CODE REVIEW

**Comment by alicetragedy** [comment]
@mkalininait this is pretty much ready from my side. The troubleshooting section under “Teams” still says work in progress, but I don't have an overview of the stuff that should go in there. Probably an issue with roles and adding members to a team? I think it could definitely be cleaned up to look a bit better, but the content is mostly done. Would you mind reviewing it when you have some time, or do you just want me to merge it?

**Comment by alicetragedy** [comment]
@mkalininait are you able to review this today, or should I go ahead and merge it?

**Comment by mkalininait** [comment]
Hey @alicetragedy Thanks for this job. The PR looks good to me. 
I'd add one minor change: `margin-top` and `margin-bottom` properties in the `img.help-image` class. It's not necessarily the subject of this PR, but since you've added this class... :) Otherwise I can add it later!

Re further improvements: I agree that we can continue working on the help pages (there is a room for improvements), but it definitely shouldn't stop us from merging this PR.

**Comment by alicetragedy** [comment]
I agree on the styles needing to be cleaned up a bit — I will merge this for now, and we can improve them further in the future. There is definitely room for improvements 🙈

**Pull request merged**
