### PR TITLE
Update form

### PR DESCRIPTION
**Pull request by F3PiX**
We are working on moving the form to this page, but we ran into problems. So, this is a temporarily solution.

### CODE REVIEW

**Comment by F3PiX** [comment]
@alicetragedy Would you merge it please? Sorry about the  stray `p`, we will solve it in the next days.

**Comment by alicetragedy** [comment]
@F3PiX I'll take a quick look at it locally, and will merge it after that :+1:

**Comment by alicetragedy** [comment]
should be fine. #yolomerge!

**Comment by roosdebildt** [comment]
haha love #yolomerge :heart:

**Pull request merged**
