### PR TITLE
Fixed a couple of text strings.

### PR DESCRIPTION
**Pull request by mkalininait**
https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/407
Fixed:
* "Some of the guidelines are specific to ruby, but most are language-agnostic." - needs to be changed
*  "For how many months have you been learning the language of your chosen project?" - doesn't mention secondary project
* "Tell us about your Rails Girls and community involvement."-> change to all initiatives

### CODE REVIEW

**Comment by alicetragedy** [comment]
just waiting for the builds before merging, but this looks good @mkalininait :+1:

**Comment by mkalininait** [comment]
Thanks @alicetragedy, the fixes are very humble, but one should start somewhere :)
Next time, should I make such little fixes in a pull request or just push directly in a branch?

**Comment by alicetragedy** [comment]
@mkalininait any fix that is a fix is a helpful fix :) 
As for the way to contribute: It's really up to you. Usually, for minor changes like this, pushing directly is really not a problem. :) If you'd prefer for someone to review your work, a PR is the way to go.

**Comment by carpodaster** [comment]
:confetti_ball:

**Pull request merged**
