### PR TITLE
Add link to rating dashboard to user navigation

### PR DESCRIPTION
**Pull request by klappradla**
Hey @mkalininait,

this adds a link to the rating dashboard to the user navigation, as described in #657. The link is displayed throughout all phases, I could not find a specification for something like a *"rating phase"* (cc @alicetragedy).

Be aware of the fact that the current implementation of the applications-table will probably not work with the current DB schema - and therefore break 💥 if you try to access it now.

### CODE REVIEW

**Comment by mkalininait** [comment]
Thank you Max @klappradla !

**Comment by klappradla** [comment]
Correct me if I'm wrong @carpodaster, but from what I remember, there were changes to the applications' data model that have not yet been reflected in the rating parts of the app. Therefore I think the big application table is not yet renderable...

**Comment by klappradla** [comment]
If you want me to adjust (in some way) the application table for this, I'd suggest to simply throw in a new issue and assign it to me. For its core functionality, I think this PR could be savely merged before that. No reason to access the applications' table now anyways.

**Comment by mkalininait** [comment]
@klappradla @carpodaster We want to come up with a list of things which need to be adjusted in the rating parts of the app this week. But it's not done yet.

**Comment by alicetragedy** [comment]
+1 on merging this. By beginning of next week we should have a full overview of the changes that need to be made to the “ratings app”, and we will not need to start rating until later in the week. :partyparrot:

**Pull request merged**
