### PR TITLE
fix for preview students updates

### PR DESCRIPTION
**Pull request by izuroxx**
@carpodaster @ramonh 
preview for status updates not working :( 

letter was missing in _form partial 
was: `.tab-pane#preview-pan`
fixed to: `.tab-pane#preview-pane`

Very sorry!

### CODE REVIEW

**Comment by ramonh** [comment]
Looks good, thanks for fixing, @izuroxx!

I'll merge as soon as the Travis is done :)

**Comment by carpodaster** [comment]
I beat you to it, @ramonh 😉  Thanks, @izuroxx !

**Comment by ramonh** [comment]
😂 Too fast for me, @carpodaster. But yes nice one!

**Comment by izuroxx** [comment]
:smile: very sorry and thank you!

**Comment by carpodaster** [comment]
No worries @izuroxx, so many pairs of eyes didn't see it. No biggy :)

**Comment by ramonh** [comment]
Exactly it happens all the time 😅

**Pull request merged**
