### PR TITLE
Add volunteering-related columns to application table

### PR DESCRIPTION
**Pull request by ramonh**
As discussed for the new selection process, this adds the "Volunteer?" and "Volunteer hours" columns to the application rating table.

### CODE REVIEW

**Comment by alicetragedy** [comment]
Something I just thought of when looking at this: do you think it would make sense to change the boolean values (`True` & `False`) to display as something like "yes" and "no" instead (using a locale or a helper method)? It's definitely not a requirement, more like an enhancement. :)

**Comment by ramonh** [comment]
Hey @alicetragedy, thanks for the feedback! 

I thought of this too, but wasn't sure what would be preferred. `Yes` and `No` sound good to me though. Will add this today 👍

**Comment by alicetragedy** [comment]
awesome, thanks @ramonh! And I think it's definitely something we can reuse — I took a quick look to see if we had anything like that but it doesn't look like it, and it might be useful for the [conferences table](https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/master/app/views/conferences/_table.html.erb#L21) too. ;)

**Comment by ramonh** [comment]
Great idea! I'll make it a huge scoped one then :)

**Comment by alicetragedy** [comment]
@ramonh did you get a chance to look at the helper method enhancement thing I suggested yesterday? or, better said: is there anything we can help you with there? I have some time today and over the weekend so am happy to jump in if needed <3

**Comment by ramonh** [comment]
Hey @alicetragedy! I've got it ready to go, just had to step out a bit earlier. Will commit and push!

**Comment by ramonh** [comment]
All set! Thanks for the patience.

**Comment by alicetragedy** [comment]
@ramonh I'm sorry, but I wasn't thinking straight... I realised that application_data["voluntary"] actually returns a string, not a boolean, and so `format_boolean` will always show “Yes” in this case. The quickest way I can think of for fixing this is a conditional checking for the content of the value (ie. if true return yes) but maybe it's kind of "dirty"? what do you think?

**Comment by ramonh** [comment]
Oh dear, good catch, @alicetragedy. I didn't think this through 😭 

I had initially misunderstood what you wrote, but I think that's a good idea! I don't think it's too dirty, because we're ensuring that we're passing the correct value type.

**Comment by ramonh** [comment]
And done! Thanks for the feedback again :)

**Comment by mkalininait** [comment]
@klappradla Do you think we can merge it (after solving the merging conflict) or does it not work well with your new application table model?

**Comment by klappradla** [comment]
Hm, it's ok to merge it, but the benefit is not huge unfortunately (sorry @ramonh), since the two files are basically gone in the new view 🙈

**Comment by ramonh** [comment]
Hey! No worries. If I understand correctly then, we should close this?

**Comment by klappradla** [comment]
Yes @ramonh. Resolving the conflicts and then merging to master just for removing the files after all is not worth the effort - you know 😉

**Comment by ramonh** [comment]
Fair point, thanks @klappradla! I'll catch up and try again

**Pull request closed without merging**
