### PR TITLE
Revert "Change project submission form for 2017"

### PR DESCRIPTION
**Pull request by nbogis**
Reverts rails-girls-summer-of-code/rgsoc-teams#553

### CODE REVIEW

**Comment by nbogis** [comment]
Hold on I'm confused. Why did I have the control to close this pull request!?

**Comment by klappradla** [comment]
Hey @nbogis, I think that's cause you're a member of the RGSoC Github organization 🙈

**Comment by carpodaster** [comment]
@nbogis as Max said, you are member of the RGSoC organisation on Github. Without being part of the org, one cannot be assigned to issues which is a good indicator for others that someone's already working on a given feature/issue.

Mishaps do happen. The master is reverted back to its previous state. It does mean some extra work so please double check the buttons you're clicking 😉

**Comment by nbogis** [comment]
thanks guys and sorry about the confusion

**Pull request merged**
