### PR TITLE
Improve header nav (mobile)

### PR DESCRIPTION
**Pull request by F3PiX**
- [x] Step 1: Added navbar-default class to header.
- [x] Step 2: Restore regular menu

Issue #335

### CODE REVIEW

**Comment by F3PiX** [comment]
@alicetragedy 
I added `navbar-default` class to the header. Now, it pushes the text out of the way. Is this the way you want to go?

Also, the regular menu is messed up now.

**Comment by alicetragedy** [comment]
@F3PiX sorry for getting back to you so late. I finally managed to take a look and yes, I think that's the way we could go. It looks good for the mobile version :)
The next step is as you outlined above to restore the regular menu. If I recall correctly the [bootstrap documentation](https://getbootstrap.com/components/#navbar) should be of great help.

**Comment by alicetragedy** [comment]
I am still looking into it @F3PiX but: I realised that first and foremost, in order to change it, the `navbar-default` should be moved out of the `ul` class (for example, into `nav.top`). 
After that, you can add a `background-color` to it. 
I think the only way to override the color of a `navbar-default` is to also add 
```
background-image: none
background-repeat: no-repeat
```
However there's still a couple of strange things happening with the css (the collapse will pick up that red color, which I am not sure we want). An alternative would be to create a `navbar-custom` class in the css (it will be the color of the navbar we currently have) and add to that extra specifications for the `collapse` (drop down menu). 

Maybe try some stuff around with the info above, I'll also dig deeper into it from my end and see if there's some totally obvious way I have not considered.

**Comment by F3PiX** [comment]
Just moving the nav_bar + menu id out of the ul did the trick! 
Regarding the other problems: I would very much not try to solve that myself. It is way over my head.  Okay? One question though: wouldn't most of the (new) problems be solved if we replace the 'header'  by a regular bootstrap navbar? At the least, I suppose Bootstrap will take good care of the dropdown menu.

**Comment by alicetragedy** [comment]
@F3PiX that's okay, I understand :)
so, it only took one more change for it to work properly (with your restoring the change, the menu was stuck collapsed in responsive view): the `collapse` class needed to be moved outside of the unordered list into its own div. I've also added `role="navigation"` to improve accessibility. 
This should now work properly as intended, and I think we can merge the PR. Great work Maud!! :tada:

**Comment by F3PiX** [comment]
:8ball: Sorry I missed that. Glad to have you watching my back! :bow:

**Comment by alicetragedy** [comment]
No worries! I think we were each other's rubber ducks ;)

**Pull request merged**
