### PR TITLE
#504 Clarify sass files

### PR DESCRIPTION
**Pull request by katrin-k**
Following issue #504 I went through all the Sass files, moved selectors to the specific files when not used overall, removed unused selectors, added some comments on non-descriptive selectors and removed an unneccessary margin. 

@agnik5 I had a merge conflict with your conference changes *dumdidum*… Could you please double-check that I used your new styles?

No pic today, since hopefully I didn't overlook anything and everything is the same as before ;).

### CODE REVIEW

**Comment by agnik5** [comment]
@katrin-k Sorry, I missed your message. Could you tell me a bit more about this merge conflict?

**Comment by katrin-k** [comment]
@agnik5 No worries. It was about the styles for `.conference dl` and `dt` (which is now in `stylesheets/controllers/conferences.sass`) that shows details of a conference.

**Comment by agnik5** [comment]
@katrin-k Is that issue already solved or your request is still pending?

**Comment by katrin-k** [comment]
@agnik5 I think, everything's good. I did resolve the merge conflict. I just didn't want to overwrite sth. you did without any word :). 

So yeah, we're good to merge :+1:

**Comment by katrin-k** [comment]
Upsi. I realize I've overwritten my own changes… *dumdidum*
I'll close this issue and open a new PR with the changes.

**Pull request closed without merging**
