### PR TITLE
Conferences/aditional info

### PR DESCRIPTION
**Pull request by juuh42dias**
Related issues  #768 and  #769

Edit teams view before additional info

edit teams view old

Edit teams view after additional info 

edit teams view new

### CODE REVIEW

**Comment by mkalininait** [comment]
Hey @juuh42dias Thank you for the PR! I've tested it (but didn't check the code).
It works well for me!

A couple of UI notes:
1) Is there a reason why the checkboxes are aligned differently that all the other fields on the form? 
2) For the "terms and conditions" checkboxes I would probably remove the current titles and use the hints instead of the titles. The short titles sound a bit unclear to me.
3) I was playing with the team edit form and I'm not that sure anymore, that we should validate the "terms and conditions" when we save the form. It may be that a user wants to edit her team's blog url, and we're kinda forcing her to check the conference terms and conditions, too. It's probably not a good UX... What do you think?

**Comment by klappradla** [comment]
Hey @juuh42dias thanx for the PR 💚 

I already looked into bits of the code and it made me wonder if the data model you chose may eventually make things harder for you as they needed to be. Therefore, can you upfront, before I dig deeper into this maybe quickly explain why you chose this data model?

I will briefly explain what I think would be a simpler approach - no need for you to take this as a source of truth and implement it like this of course! Please feel fee to always ping me on Slack if something is unclear or I need to explain things in more detail _(I reduced my active Slack teams to < 10 in the last week - should be able to respond fairly quick now)_

**How to add new attributes?**
I have two possible approaches, which depends on how the new `comment`, `lightning_talk` etc. attributes should be added to the `ConferencePreference` model. I would also love to have a word by @mkalininait on this, how it makes most sense for you. I see two approaches:
1. ONE `comment`, `lightning_talk` etc. for ALL preferences
1. ONE `comment`, `lightning_talk` etc. for PER preference _(different to how it is implemented in this PR)_

### 1. ONE `comment`, `lightning_talk` etc. for ALL preferences
_(this is the approach you chose - telling from e.g. the screenshot)_

If we take the `ConferencePreference` model as a starting point for orga users later on confirming actual attendences, it would be easiest to have the whole thing as one entity on the `Team`. So instead of having a `conference_id` and an `option` attribute on the model, it could also look like this:
```ruby
create_table "conference_preferences", id: :serial, force: :cascade do |t|
  t.bigint "team_id"
  t.bigint "conference1_id"
  t.bigint "conference2_id"
# etc.
```

If done like this, there's also no reason for an additional `ConferencePreferenceInfo` model - all the attributes, e.g. the `comment` can simply be added to the `ConferencePreference` object itself, so you end up with a simple 1 x 1 association between the `Team` and the `ConferencePreference` object:

untitled diagram 1


In terms of Rails, this afaik basically just means, the `ConferencePreference` model has two belongs-to associations to the `Conference` table:
```ruby
class ConferencePreference
  belongs_to :conference1, foreign_key: "conference1_id", class_name: "Conference"
  belongs_to :conference2, foreign_key: "conference2_id", class_name: "Conference"
```

For the two `terms_and_condition` types of check-boxes: these in my opinion can also be "virtual" attributes not persisted to the DB but only present on the object instance. Maybe take look at ActiveRecord's [acceptance type of validation](http://guides.rubyonrails.org/active_record_validations.html#acceptance).

### 2 ONE `comment`, `lightning_talk` etc. for PER preference
_(different to how you implemented it in this PR)_

For this approach, I'd also spare out the `ConferencePreferenceInfo` model and instead add the new attributes straight onto the `ConferencePreference` model. This approximately looks like this:

untitled diagram 2

Again, the `terms_and_condition` checkboxes can probably be added as non-persisted attributes.

### Pros / Cons / Preferences
Depending on @mkalininait 's initial idea of this, I'd personally prefer the first approach, since it's just the simplest way possible. There's not even the need to validate the number of `ConferencePrefereces` per `Team` (since it will always be just one), etc.

Of course, the requirements may potentially change within the next years, but I'm personally not a huge fan of building things more complex upfront for things that *"may*" eventually come 😉 

I'm putting this on "request changes" just for this question I have here _(it helps me to keep track of my Github notifications if I already see, that I did an initial review on this)_

**Comment by juuh42dias** [comment]
Hi, @klappradla :) 

So, we created the cp_info model because we would have more autonomy in controlling the information related to the team who chose the conference_preferences. Even if there are not any changes soon, the table already allows modifications in a way that avoids much future rework. In other words, we thought this implementation would allow us to easily introduce changes that belong to one of the preferences or even to both. We have suggested this approach for @Maria, but if you want we can change it.

**Comment by klappradla** [comment]
Ah alright @juuh42dias, thanx for coming back to my question so quick 🙏 

I tbh don't see the benefit it a lesser coupling between `ConferencePreference` and `ConferencePreferenceInfo`. The benefit of being able to then easier add new team-related attributes to it comes at the cost of having to maintain the way a way more complex association tree, a more complex form, etc., together with making sure, all of these objects depending on each other are available in the right moment and are deleted in the right moment.

So in my opinion, the maintenance and complexity overhead is too high a price for the benefits.

Aside that: I think the question whether there's **one info block per `Team`** vs. one info block per `ConferencePreference` should be answered before. It also does not make much sense to implement it it a way loose enough to be able to jump between these two things in my opinion. None foresees the future, so there's no point in introducing complexity and technical dept for requirements that may never come 🐌

**Comment by mkalininait** [comment]
Hey @klappradla Thanks for the input!
The idea was to implement the "1. ONE comment, lightning_talk etc. for ALL preferences" strategy. I agree that it should be sufficient to have the `ConferencePreference` model and I don't see why we need the `ConferencePreferenceInfo` model.

We indeed discussed the models with @juuh42dias and Amanda some days ago; I looked to me that we agreed on exactly the same solution tbh. Maybe I misunderstood you @juuh42dias ? If so, I'm sorry! I thought we were on the same page.

**Comment by klappradla** [comment]
Yay @mkalininait ✌️ - guess we're at least all on the same page _now_ 😉

**Comment by juuh42dias** [comment]
1. ONE comment, lightning_talk etc. for ALL preferences.

@mkalininait  sounds good for me (too). I'm already implementing this new version of the relations.

**Comment by juuh42dias** [comment]
@mkalininait @klappradla 
So, i think is better create a new PR with new changes, that's ok? :smile_cat:

**Comment by mkalininait** [comment]
@juuh42dias This is ok with me :)

**Comment by klappradla** [comment]
Alright @juuh42dias, so I'm closing this one, since you're working on a new one now ✌️

**Pull request closed without merging**
